[theme]
primaryColor = "#0E8176"
backgroundColor = "#F7F5EF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17213B"
font = "sans-serif"

[browser]
gatherUsageStats = false

[server]
headless = true
